# Generated by Django 3.0.8 on 2020-07-25 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='team',
            new_name='board',
        ),
    ]
